### ISSUE TITLE
prediction probability in the output

### ISSUE THREAD

**Issue by alcrevenna** [BBQuercus/deepBlink#118]
**Would it be possible to get as part of the output the prediction probability**
First of all, great tool. 
I'd like to use this for spatial transcriptomics (ISS or seqFISH). I am looking in particular at trying out this code:
https://github.com/wahlby-lab/graph-iss
that requires the prediction probability as an input. I guess from the last layer of your network there is also a probability with the proposed object being detected. Would it be possible to output that too?
thanks,
Alvaro

**Comment by BBQuercus** [comment]
Hey, thanks for your input. We can add a prediction probability as well. Would the following behaviour suit your needs:

- `deepblink predict ... --probability <float>`
- If `--probability` is passed, you can override the default rounding (probability >0.5) by passing in your own value
- Additionally, output of a "p" / probability column in the output csv file

Let us now if that works and we'll try to get it done soon.

**Comment by alcrevenna** [comment]
Thanks for the prompt reply. Yes, having those two features, being able to chose the threshold for detection and having the outout p on the csv file is exactly what I am looking for. Thanks!

**Comment by BBQuercus** [comment]
👍 We'll let you know once it's done. Hopefully by next week.

**Comment by alcrevenna** [comment]
Hi, just one question: to train my own data, I see that the number sort of depends on the intensity distribution of my objects, but what about image size? Could I use say 512x512 or should it match exactly to whatever it will be my 'tile size' in the future. In spatial transcriptomics we're interested to image a large area (say 1cm^2) tiled in many small areas.

**Comment by BBQuercus** [comment]
Tile-size and training size don't need to match up. We usually train on 512x512 to better fit into GPU memory but now predict on larger images (1024) on the CPU.

**Comment by BBQuercus** [comment]
It should all be there now as described. Check PR #119 for a quick example. I'll close the issue if this resolved it. Changes will be made available on pypi next week (or already via GitHub).

**Comment by mimuelle** [comment]
Is there an update on this issue?  I would also be very interested in this feature.

**Comment by BBQuercus** [comment]
Once PR #121 is merged, I'll upload the next version later today.
