### ISSUE TITLE
Comparison between deepBlink and spotlearn

### ISSUE THREAD

**Issue by imzhangyd** [BBQuercus/deepBlink#143]
@BBQuercus Hi, thanks for your great work! I learn a lot from it.
I didn't find the performance of spotlearn in paper, whose code in this repository. So I'm curious about the performacne comparison between deepBlink and spotlearn, both base Unet structure.
Looking forward to your reply :)

**Comment by BBQuercus** [comment]
Hey,

Glad you're liking deepBlink.

We originally wanted to include SpotLearn but given that they only predict binary masks and don't do true spot localization, we didn't feel confident in comparing apples with (maybe not quite oranges but) pears. We therefore had to convert coordinates to binary object which wasn't ideal. On the datasets we tested it performed reasonably well after sweeping different spot sizes for less dense spots but struggled as spots got more dense (which was to be expected). Overall, deepBlink was able to beat them on all but one dataset fairly well if I recall correctly.

Additionally, the models ended up being almost twice as large and with all pre/post-processing required quite a bit slower.

Best
