### ISSUE TITLE
deepblink model

### ISSUE THREAD

**Issue by wikk-chy** [BBQuercus/deepBlink#146]
**Describe the bug**
deepblink is significant for us to deal with FISH images. 
When I create a npz file to train model, I find it there is something different.
I wonder why the image_arry.min is not 0.
![}5885FLY4I~BSLT6(6S@ 7A](https://user-images.githubusercontent.com/96384394/200123303-d9f68af3-6279-4d34-a33c-759e902e775e.png)
After this I test the model trainning by my npz, it can only call spots which are backgrounds.like this
![image](https://user-images.githubusercontent.com/96384394/200123560-adfbda43-898f-44a9-9607-3e80ed21bebf.png)
I don't know if the num of image_arry influence the results.
And also I have checked the image dtype from my npz and smfish.npz, there is no difference.
![1B3_~O M% @1@88R%YE7EV](https://user-images.githubusercontent.com/96384394/200123698-7445c6ee-f8b0-41e1-9833-9e87c36a3b7c.png)
Finally, I look forward to receiving your reply.
Thank you!

**Versions:**
 - OS: Linux version 4.18.0
 - Python Version: 3.8.13
 - deepBlink Version：0.1.3

**Comment by BBQuercus** [comment]
Hi, thanks for raising the issue. This indeed looks a bit wonky. I'd suggest two things to get an overview:
* Use `deepblink visualize` to check how the labels in your dataset look like. Just pass the npz file with the `--dataset` flag. It'll open a matplolib viewer so just make sure you're doing it somewhere with a GUI.
* Send us your npz file so we can have a look - ideally together with the config file used for training to see what might have gone wrong.

**Comment by wikk-chy** [comment]
Thanks for response, may I send the npz and config file to Email: bastian.eichenberger@fmi.ch. If the address is working, I'll send tomorrow as it's time to have a rest in China haha.

**Comment by wikk-chy** [comment]
Hi, sorry to interrupt again.
My file_names are like the sample below. However, when I create the npz file as the following order, there is still the problem that the images and labels can not match up.
![图片](https://user-images.githubusercontent.com/96384394/200228926-8a5c6de0-29a0-4d73-bc14-fda9b5a0a924.png)
![图片](https://user-images.githubusercontent.com/96384394/200228999-4b82529d-d858-47d9-9fa4-e74fef3c8880.png)
Also, I have tried the paremeter --label and get the same result.

**Comment by BBQuercus** [comment]
Hmm, can you send me a few of your images and labels (same way as before) - I'm not quite sure what it could cause but it's easiest to check with what you have.

**Comment by wikk-chy** [comment]
I save the npz by my own def as your format , and it is working now. Indeed, I still wonder which way to name the file can create the npz file by your CLI which I think is more convenient for us to use deepblink.

**Comment by BBQuercus** [comment]
I replied by mail - I think it was just the labels for X and Y being swapped. Maybe try that and see if the CLI works as it should. Otherwise just let us know if your model is now predicting things properly so we can close the issue.
