### ISSUE TITLE
Benchmark of DetNet and spotlearn

### ISSUE THREAD

**Issue by wikk-chy** [BBQuercus/deepBlink#151]
**Describe the bug**
While I want to train DetNet model with smfish.npz, there is occurred to '[1]    3390102 segmentation fault (core dumped)' .
And then I checked the script detnet_train.py, however, I could not find the source of main problems.
In addtional, I think there might be train_imgs in the box pointed by the red arrow.
**To Reproduce**
1. Using data "smfish.npz" "myown.npz"
2. Running "python ../deepBlink-master/benchmarks/detnet/detnet_train.py --dataset ../smfish.npz  --savedir DetNet"
3. See error [1]    3390102 segmentation fault (core dumped)

**Expected behavior**
Training  and testing DetNet and spotlearn 

**Screenshots**
![image](https://github.com/BBQuercus/deepBlink/assets/96384394/b66342c0-8f7c-4299-be8c-b1b213864e78)
![image](https://github.com/BBQuercus/deepBlink/assets/96384394/b7a288cd-62ae-432c-a173-06d5ce5480b0)

**Versions:**
 - OS: Linux
 - Python Version: Python 3.9.18
 - deepBlink Version deepblink 0.1.4

**Additional context**
The same problem while trainning spotlearn.
I have followed deepblink more than 1 year. 
Using the model to deal with some FISH images and due to the good job, the results are really reliable.
Finally, looking forward to your reply :)

**Comment by zhanyinx** [comment]
Hey there, 

Thanks for using our tools and sorry for the late reply. We will fix the bug you pointed out in the detnet benchmark.
Regarding the segmentation fault issue, can you give us more details on the resources you are using (GPU memory, CPUs etc)?

**Comment by wikk-chy** [comment]
Hi, thank you for your response.

It seems that this error is not caused by memory or GPU memory limitations. I have reproduced DetNet and spotlearn using PyTorch and tested the networks. I will close this issue. Thanks again for your reply. Lastly, sending good wishes to you.
