### ISSUE TITLE
Convert prediction matrix dataset into coordinates

### ISSUE THREAD

**Issue by BBQuercus** [BBQuercus/deepBlink#59]
**Is your feature request related to a problem? Please describe.**
Currently all datasets use prediction matrices as labels instead of coordinates. This has the unfortunate consequence of not allowing simple changes to matrix grid size and the necessity of changing all matrices to coordinates in benchmarking costing valuable time.

**Describe the solution you'd like**
Multiple changes required:

- [x] Datasets: script to convert existing matrices to coordinates using same datasets to avoid affecting trained models on the current train/val split.
- [x] Training: decide if conversion of coordinates to matrix should occur before training loop (`cls Dataset init`) or during the loop (`cls SequenceDataset getter`). **Decision** - As datasets are currently all loaded into memory (not read from file at runtime), it makes sense to convert coordinates to matrices once data is loaded. This way, we avoid slowing down training due to a CPU bottleneck.
- [x] Benchmarking: all four benchmarking scripts currently in development - remove `true` conversion at testing time and `label` conversion before training.
- [x] Network: In addition, because prediction matrices are computed just before training time, cell_size needs to not only be used to compute the matrix but also to change the model architecture providing a proper output.

**Comment by zhanyinx** [comment]
Datasets problem: I think we can use the get_coordinate_list function
Training: in dataset init, so we do it only once

**Comment by BBQuercus** [comment]
Not fully solved (network and l2 loss) but enough for now.
